use_frameworks!

platform :ios, '10.0'

target 'Textile_Example' do
  pod 'Textile', :path => '../'

  target 'Textile_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
